---
title: Va
timezone: UTC
collections:
  gallery:
    title: Galerie
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
<<<<<<< HEAD
  -
    scope:
      path: ""
      type: "gallery"
    values:
      thumbnail_path: ""
      image_path: ""
      caption: ""
=======
- scope:
    path: ''
    type: gallery
  values:
    thumbnail_path: ''
    image_path: ''
    caption: ''
    description: ''
>>>>>>> origin/master
