---
title: Va
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  gallery:
    title: Galerie
defaults:
  -
    scope:
      path: ""
      type: "gallery"
    values:
      thumbnail_path: ""
      image_path: ""
      caption: ""
      description: ""
