---
title: Va
timezone: UTC
collections:
  gallery:
    title: Galerie
    output: false
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: gallery
  values:
    thumbnail_path: ''
    image_path: ''
    caption: ''
    description: ''
